"""
Django settings for grshop project.

Generated by 'django-admin startproject' using Django 3.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-_x!f^5o+ih7=b7ae(dyhqs&ihug)t+pabvkh&$e09whp3hlu#a'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'polymorphic',
    'main',
    'mptt',
    'cart',
    'promo',
    'users'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'grshop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'cart.context_processors.cart',
                'promo.context_processors.promos'
            ],
        },
    },
]

WSGI_APPLICATION = 'grshop.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/uploads/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'uploads/')

SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_COOKIE_AGE = 604800
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_COOKIE_DOMAIN = None
CART_SESSION_ID = 'grshop_cart'

# CART SETTINGS
TYPES_OF_TOASTS = {"PRODUCT_HAS_ADDED": "product added",
                   "PRODUCT_HAS_DELETED": 'product deleted'}

# USERS SETTINGS
AUTH_USER_MODEL = 'users.UserBase'
LOGIN_REDIRECT_URL = '/user/dashboard'
LOGIN_URL = 'user/login'
REGISTRATION_SUCCESS_TEXT = '''Your registration was successful.
                            You need to activate your account for use on the site. 
                            An email was sent to you with an activation link and further instructions.'''

# #MAIL SETTINGS
SENDING_EMAIL_OFF = True
DEFAULT_FROM_EMAIL = 'admin@mail.com'
# SERVER_EMAIL = 'admin@mail.com'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_USE_TLS = True
# EMAIL_HOST = 'mail.gmail.com'
# EMAIL_HOST_USER = 'email'
# EMAIL_HOST_PASSWORD = 'password'
# EMAIL_PORT = 587


# ORDERS SETTINGS
STATUS = {'NEW': 'new order',
          'IN_PROGRESS': 'order in progress',
          'READY': 'order is ready to delivery/self picking up',
          'STATUS_COMPLETED': 'order is completed'}

DELIVERY_TYPE = {"SELF": "self",
                 "STANDARD_DELIVERY": "standard delivery"}

AVAILABLE_DELIVERY_TYPE = ['SELF']

BILLING_STATUS = {"NOT_PAID": 'not paid',
                  "PART_PAID": 'paid particularly',
                  "FULL_PAID": 'full paid'}

BILLING_TYPE = {"IN_OFFICE": "in office by self picking up",
                "CARD_ON_SITE": "card on site now"}

AVAILABLE_BILLING_TYPE = ['IN_OFFICE']