# Generated by Django 3.2.5 on 2021-07-24 07:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('promo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountInStock',
            fields=[
                ('promo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='promo.promo')),
                ('need_min_stock_count', models.PositiveIntegerField(default=5, verbose_name='Stock of product need')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('promo.promo',),
        ),
        migrations.CreateModel(
            name='ProductGroupDiscount',
            fields=[
                ('promo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='promo.promo')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('promo.promo',),
        ),
        migrations.CreateModel(
            name='SimpleDiscount',
            fields=[
                ('promo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='promo.promo')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('promo.promo',),
        ),
        migrations.AddField(
            model_name='promo',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_promo.promo_set+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='promo',
            name='promo_code',
            field=models.CharField(default='iXn1mz', max_length=255, verbose_name='Promotion code'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 23, 17, 48, 57, 842145), verbose_name='End date and time'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 24, 17, 48, 57, 842145), verbose_name='Start date and time'),
        ),
    ]
