# Generated by Django 3.2.5 on 2021-07-24 08:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0002_auto_20210724_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 23, 18, 37, 58, 338457), verbose_name='End date and time'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='promo_code',
            field=models.CharField(default='RIHZ0W', max_length=255, verbose_name='Promotion code'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 24, 18, 37, 58, 337457), verbose_name='Start date and time'),
        ),
    ]
