# Generated by Django 3.2.5 on 2021-07-25 02:44

import datetime
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0003_auto_20210724_1837'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='countinstock',
            managers=[
                ('promo_manager', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='productgroupdiscount',
            managers=[
                ('promo_manager', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='promo',
            managers=[
                ('promo_manager', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='simplediscount',
            managers=[
                ('promo_manager', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='promo',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 24, 12, 44, 38, 568608), verbose_name='End date and time'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='promo_code',
            field=models.CharField(default='NDLEOR', max_length=255, verbose_name='Promotion code'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 25, 12, 44, 38, 568608), verbose_name='Start date and time'),
        ),
    ]
