# Generated by Django 3.2.5 on 2021-07-25 03:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0004_auto_20210725_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 24, 13, 25, 56, 522348), verbose_name='End date and time'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='promo_code',
            field=models.CharField(default='DUQJCB', max_length=255, verbose_name='Promotion code'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 25, 13, 25, 56, 522348), verbose_name='Start date and time'),
        ),
    ]
