# Generated by Django 3.2.5 on 2021-07-26 03:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0005_auto_20210725_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 25, 13, 8, 1, 106517), verbose_name='End date and time'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='promo_code',
            field=models.CharField(default='0KO3QB', max_length=255, verbose_name='Promotion code'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 26, 13, 8, 1, 106517), verbose_name='Start date and time'),
        ),
    ]
