# Generated by Django 3.2.5 on 2021-07-23 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='on_front',
            field=models.BooleanField(default=False),
        ),
    ]
