# Generated by Django 3.2.5 on 2021-07-24 04:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 23, 14, 13, 17, 684790), verbose_name='End date and time'),
        ),
        migrations.AddField(
            model_name='promo',
            name='start_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Start date and time'),
        ),
    ]
