# Generated by Django 3.2.5 on 2021-07-24 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210724_1417'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Promo',
        ),
    ]
