# Generated by Django 3.2.5 on 2021-07-24 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_delete_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='specification',
            field=models.FileField(blank=True, upload_to='specifications/', verbose_name='Specification File'),
        ),
    ]
