# Generated by Django 3.2.5 on 2021-07-26 03:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0010_product_specification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('country', models.CharField(blank=True, max_length=20)),
                ('area', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(blank=True, max_length=150)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('postcode', models.CharField(blank=True, max_length=12)),
                ('status', models.CharField(choices=[('NEW', 'new order'), ('IN_PROGRESS', 'order in progress'), ('READY', 'order is ready to delivery/self picking up'), ('STATUS_COMPLETED', 'order is completed')], default='new order', max_length=100, verbose_name='Order status')),
                ('delivery_type', models.CharField(choices=[('SELF', 'self'), ('STANDARD_DELIVERY', 'standard delivery')], default='standard delivery', max_length=100, verbose_name='Delivery type')),
                ('billing_status', models.CharField(choices=[('NOT_PAID', 'not paid'), ('PART_PAID', 'paid particularly'), ('FULL_PAID', 'full paid')], default='not paid', max_length=100, verbose_name='Billing status')),
                ('billing_type', models.CharField(choices=[('IN_OFFICE', 'in office by self picking up'), ('CARD_ON_SITE', 'card on site now')], default='in office by self picking up', max_length=100, verbose_name='Billing type')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Additional Information')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date of order creation', verbose_name='Creation date')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Date of last order update', verbose_name='Updating date')),
                ('order_hash', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_orders', to=settings.AUTH_USER_MODEL, verbose_name='Customer')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Price')),
                ('count', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='main.product')),
            ],
        ),
    ]
